### ISSUE TITLE
The box 'bento/centos-7.2' could not be found.

### ISSUE THREAD

**Issue by Bystroushaak** [WebArchivCZ/machines#2]
Nechtělo by to tu cestu nastavovat nějak dynamicky?

```
$ vagrant up
Bringing machine 'seeder' up with 'virtualbox' provider...
Bringing machine 'db' up with 'virtualbox' provider...
Bringing machine 'sentry' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* The following settings shouldn't exist: insert_key

vm:
* The box 'bento/centos-7.2' could not be found.
```

![instruction_unclear](https://cloud.githubusercontent.com/assets/227282/13248701/32625a7a-da20-11e5-92df-46310c766d01.png)

**Comment by westfood** [comment]
hele, 

ad box could not be found) to bentos/centos-7.2 by mělo právě fungovat tak, že si to najde na netu a nainstalluje.
ad ssh - insert_key, jakou máš verzi vagrant?

r.

**Comment by Bystroushaak** [comment]
Vagrant 1.4.3

Jsem tam asi nedal to heslo, mi teď tak dochází.

No, každopádně z netu to nic netahá.

**Comment by Bystroushaak** [comment]
Nemělo by tam být `c.vm.box_url`?

**Comment by westfood** [comment]
Hm… jedeš old school. Imho to je nějaký instrukce, co ještě není v tvé verzi.. ještě ti pošlu tu heslo, jen co ho zahesluje resolverovským gpg…

Vagrant 1.8.1
ansible 2.0.0.2

r.

**Comment by Bystroushaak** [comment]
Aha. Já to teď instaloval z repozitářů. Natáhnu PPA.

**Comment by Bystroushaak** [comment]
Jop, vyřešeno.
